# Generated by Django 5.2.4 on 2025-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelapp", "0028_bookpackage_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookflight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="hotel_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bookhotel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookpackage",
            name="hotel_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bookpackage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="famous",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
