# Generated by Django 5.2.4 on 2025-11-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelapp", "0029_alter_bookflight_id_alter_bookhotel_hotel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookflight",
            name="passenger_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookflight",
            name="passenger_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="bookflight",
            name="passenger_id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bookflight",
            name="passenger_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookflight",
            name="passenger_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookhotel",
            name="guest_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookhotel",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="bookhotel",
            name="guest_id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bookhotel",
            name="guest_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookhotel",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="passenger_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="passenger_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="passenger_id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="passenger_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="passenger_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
