# Generated by Django 5.2.4 on 2025-11-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelapp", "0030_bookflight_passenger_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("package", "Package"),
                        ],
                        max_length=20,
                    ),
                ),
                ("booking_id", models.IntegerField()),
                ("passenger_number", models.IntegerField(default=1)),
                ("passenger_name", models.CharField(max_length=200)),
                ("passenger_email", models.EmailField(max_length=254)),
                ("passenger_phone", models.CharField(max_length=20)),
                ("passenger_address", models.TextField()),
                (
                    "passenger_id_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "unique_together": {("booking_type", "booking_id", "passenger_number")},
            },
        ),
    ]
